isa: RISCV64
cpu_model: RiscvO3CPU
cores: 2
frequency_ghz: 1
issue_width: 2

l1i_cache_kib: 16
l1i_associativity: 2
l1i_latency_cycles: 2

l1d_cache_kib: 64
l1d_associativity: 4
l1d_latency_cycles: 2

l2_cache_kib: 1024
l2_associativity: 8
l2_latency_cycles: 20

memory_type: DDR3_1600_8x8
memory_size_mib: 16
simulation_mode: SE

software_threads: 2
